class Target:
    def method(self): return 'target'
    def raise_error(self): raise Exception('エラーです。')
